services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "StrongPass@123"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
      
